---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [master, main, prod, dev]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main, prod, dev]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
#brunomartinspro I think the OUTPUT_FORMAT parameter is required for a file to be generated.
super-linter/lib/linter.sh

Lines 1028 to 1038 in f5752cf

 # Prints output report if enabled # 
 ################################### 
 if [ -z "${FORMAT_REPORT}" ]; then 
   info "Reports generated in folder ${REPORT_OUTPUT_FOLDER}" 
   ############################################# 
   # Print info on reports that were generated # 
   ############################################# 
   info "Contents of report folder:" 
   OUTPUT_CONTENTS_CMD=$(ls "${REPORT_OUTPUT_FOLDER}") 
   info "$OUTPUT_CONTENTS_CMD" 
 fi 
I was running into the same problem and came across this issue (thanks for opening it!)

This excerpt works for me:

      - name: Check coding standards
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PHP_PHPCS: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          OUTPUT_DETAILS: detailed
          OUTPUT_FORMAT: tap
      - name: Upload Report as an artifact
        uses: actions/upload-artifact@master
        with:
          name: linter-report
          path: "${{ github.workspace }}/super-linter.report/"

